
MODID_TILE0 = 0x04
MODID_TILE1 = 0x05
MODID_TILE2 = 0x06
MODID_TILE3 = 0x24
MODID_TILE4 = 0x25
MODID_TILE5 = 0x00
MODID_TILE6 = 0x01
MODID_TILE7 = 0x20
MODID_TILE8 = 0x21

MODID_PM0 = MODID_TILE1
MODID_PM1 = MODID_TILE4
MODID_PM2 = MODID_TILE6
MODID_PM3 = MODID_TILE8

MODID_PMS = [
    MODID_PM0,
    MODID_PM1,
    MODID_PM2,
    MODID_PM3
]

MODID_C2C_WEST  = MODID_TILE0
MODID_C2C_NORTH = MODID_TILE3
MODID_C2C_SOUTH = MODID_TILE5
MODID_C2C_EAST  = MODID_TILE7

MODID_PERIPHERY = MODID_TILE2

MODID_ROUTER0 = 0x07
MODID_ROUTER1 = 0x27
MODID_ROUTER2 = 0x03
MODID_ROUTER3 = 0x23

MODID_ROUTER = [MODID_ROUTER0,
                MODID_ROUTER1,
                MODID_ROUTER2,
                MODID_ROUTER3]

MODID_TO_TILE = {
    MODID_PM0 : "PM0",
    MODID_PM1 : "PM1",
    MODID_PM2 : "PM2",
    MODID_PM3 : "PM3",
    MODID_C2C_EAST : "C2C_EAST",
    MODID_C2C_SOUTH : "C2C_SOUTH",
    MODID_C2C_NORTH : "C2C_NORTH",
    MODID_C2C_WEST : "C2C_WEST",
    MODID_PERIPHERY : "PERIPHERY"
}
