
MODID_TILE0  = 0x04
MODID_TILE1  = 0x05
MODID_TILE2  = 0x06
MODID_TILE3  = 0x24
MODID_TILE4  = 0x25
MODID_TILE5  = 0x26
MODID_TILE6  = 0x00
MODID_TILE7  = 0x01
MODID_TILE8  = 0x02
MODID_TILE9  = 0x20
MODID_TILE10 = 0x21
MODID_TILE11 = 0x22

MODID_PM0 = MODID_TILE2
MODID_PM1 = MODID_TILE4
MODID_PM2 = MODID_TILE5
MODID_PM3 = MODID_TILE6
MODID_PM4 = MODID_TILE7
MODID_PM5 = MODID_TILE8
MODID_PM6 = MODID_TILE9
MODID_PM7 = MODID_TILE10

MODID_PMS = [MODID_PM0,
             MODID_PM1,
             MODID_PM2,
             MODID_PM3,
             MODID_PM4,
             MODID_PM5,
             MODID_PM6,
             MODID_PM7]

MODID_UART  = MODID_TILE0
MODID_ETH   = MODID_TILE1
MODID_DRAM1 = MODID_TILE3
MODID_DRAM2 = MODID_TILE11

MODID_ROUTER0 = 0x07
MODID_ROUTER1 = 0x27
MODID_ROUTER2 = 0x03
MODID_ROUTER3 = 0x23

MODID_ROUTER = [MODID_ROUTER0,
                MODID_ROUTER1,
                MODID_ROUTER2,
                MODID_ROUTER3]

MODID_TO_TILE = {
    MODID_PM0 : "PM0",
    MODID_PM1 : "PM1",
    MODID_PM2 : "PM2",
    MODID_PM3 : "PM3",
    MODID_PM4 : "PM4",
    MODID_PM5 : "PM5",
    MODID_PM6 : "PM6",
    MODID_PM7 : "PM7",
    MODID_DRAM1 : "DRAM1",
    MODID_DRAM2 : "DRAM2",
    MODID_ETH : "ETH",
}
